site:
  title: Open Docs
  start_page: project-pippo::index.adoc
content:
  sources:
  - url: .
    branches: HEAD
    start_path: project-pippo
  - url: .
    branches: HEAD
    start_path: project-pluto
  - url: https://github.com/ThomasVitale/test-project.git
    branches: ~
    tags: v*
    start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
urls:
  latest_version_segment: latest